<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Madys_HideNSeek</AssemblyName>
    <Version>1.0.4</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GameDir>C:\Users\Adam\BrowserDownloads\Big Walk</GameDir>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Presets\MadysDefault.json" LogicalName="BundledPresets.MadysDefault.json" />
    <EmbeddedResource Include="Presets\Essentials.json" LogicalName="BundledPresets.Essentials.json" />
    <EmbeddedResource Include="Presets\Blank.json" LogicalName="BundledPresets.Blank.json" />
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameDir)\BepInEx\interop\Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameDir)/BepInEx/core/0Harmony.dll</HintPath></Reference>
    <Reference Include="Mirror"><Aliases>global,MirrorNative</Aliases><HintPath>$(GameDir)\BepInEx\interop\Mirror.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameDir)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameDir)\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameDir)\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(GameDir)\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath></Reference>
    <Reference Include="Il2Cppmscorlib"><HintPath>$(GameDir)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath></Reference>
  </ItemGroup>
</Project>
